### ISSUE TITLE
Looking for help

### ISSUE THREAD

**Issue by veelenga** [veelenga/awesome-crystal#223]
I'm happy to say I'm looking for a new collaborator to help to support this list. Someone who has a fresh glance on maintenance, ready to collaborate with contributors and **will have fun working** on this... 

Responsibilities:

* search/add new awesome entries to the list periodically
* review/merge/dismiss new pull requests 
* remove outdated and fix broken/moved entries

The one will need to spend up to 30 minutes per week. Notice, I'm still on the track, but my priorities are changing and I will look into this less often.

If you are interested, say about this in the comments or contact me privately. I will keep this open for a couple of days.

**Comment by vladfaust** [comment]
Nice. I'm glad it's moving on :+1: 

### Some points related to Awesome List:

First of all, the list has to be **awesome**, that means no bullshit. IMO **all** shards have to:
 - Be tagged with version tags
 - Have tests 
 - Have a certain amount of usefulness, be reusable throughout a vast amount of possible projects

I also propose to introduce some kind of health meters based on dependencies status, open issues and crystal version compatibility. Maybe it worth developing a service which asserts shards against these criterias.

### Crystal ANN

In addition, I don't like current implementation of Crystal ANN. It has to be curated, not _"anyone can add their gist-shards"_. It has to have a e-mail newsletter (it may already, but I haven't noticed).

### Me

I'm happy with Crystal. Again, it's the best thing in my programmer's life. I can't develop on Ruby anymore because of knowing that I could do it better with Crystal. It's my curse also, because there is a lack of needed libraries and I don't have so much time to implement them all.

About time. ATM I'm on my way for creating a next big project with passive income (built with Crystal ofc). When I have money - I have time. I'm a creative person with a passion for programming. But the reality tells me to put my time in profit projects. I wish I could let myself to work on Crystal much more.

I need time and in the nearest future I hope I could take a major part in all this Crystal Community stuff.

**Comment by tbrand** [comment]
Could you add me to it?:heart:
Would like to work on it!

**Comment by hugoabonizio** [comment]
I would be glad to help too :smile:

**Comment by veelenga** [comment]
@tbrand @hugoabonizio welcome on board!

**Comment by hugoabonizio** [comment]
Thanks @veelenga! :)

**Comment by RX14** [comment]
@veelenga i'd be happy to review some PR's and libraries too, although i'd probably forget to do periodic things such as cleanup lol

**Comment by tbrand** [comment]
Thanks!

**Comment by veelenga** [comment]
@RX14 would love to see your reviews too ;)
